### PR TITLE
Update library for current netlink

### PR DESCRIPTION
**Pull request by SuperQ**
Update the library to be compatible with the latest netlink library
master.

/cc @mdlayher

### CODE REVIEW

**Comment by mdlayher** [comment]
I don't have commit access to this repository. It may be best to proceed with a forked version.

**Comment by SuperQ** [comment]
Maybe we could fork this into the prometheus org?

**Comment by ema** [comment]
I haven't had much time lately to work on qdisc. @mdlayher I've added you as a collaborator, hope that helps!

**Comment by detailyang** [comment]
go mod replace works and I agree to fork it int to the Prometheus org

**Comment by SuperQ** [comment]
No need to fork if @ema is willing to invite collaborators. :-D

**Pull request merged**
